//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axantum.AxCrypt.Core.Test.Properties {
    using Runtime;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axantum.AxCrypt.Core.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of David Copperfield, by Charles Dickens
        ///
        ///This eBook is for the use of anyone anywhere at no cost and with
        ///almost no restrictions whatsoever.  You may copy it, give it away or
        ///re-use it under the terms of the Project Gutenberg License included
        ///with this eBook or online at www.gutenberg.org
        ///
        ///
        ///Title: David Copperfield
        ///
        ///Author: Charles Dickens
        ///
        ///Release Date: December, 1996  [Etext #766]
        ///Posting Date: November 24, 2009
        ///
        ///Language: English
        ///
        ///
        ///*** START OF THIS PROJECT G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string david_copperfield {
            get {
                return ResourceManager.GetString("david_copperfield", resourceCulture);
            }
        }
        
        internal static byte[] david_copperfield_key__aa_ae_oe__ulu_txt {
            get {
                object obj = ResourceManager.GetObject("david_copperfield_key__aa_ae_oe__ulu_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] helloworld_key_a_txt {
            get {
                object obj = ResourceManager.GetObject("helloworld_key_a_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tst_0_0b6_key__aaaeoe__medium_html {
            get {
                object obj = ResourceManager.GetObject("tst_0_0b6_key__aaaeoe__medium_html", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] uncompressable_zip {
            get {
                object obj = ResourceManager.GetObject("uncompressable_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
