//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axantum.AxCrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axantum.AxCrypt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activefilegreen16 {
            get {
                object obj = ResourceManager.GetObject("activefilegreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to Open.
        /// </summary>
        internal static string ActiveFileKnownKeyToolTip {
            get {
                return ResourceManager.GetString("ActiveFileKnownKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to enter passphrase and Open.
        /// </summary>
        internal static string ActiveFileToolTip {
            get {
                return ResourceManager.GetString("ActiveFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source File Encryption for Windows
        ///
        ///Includes software from http://www.bouncycastle.org/ ..
        /// </summary>
        internal static string AxCryptAboutDescription {
            get {
                return ResourceManager.GetString("AxCryptAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt File Encryption.
        /// </summary>
        internal static string AxCryptFileEncryption {
            get {
                return ResourceManager.GetString("AxCryptFileEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon axcrypticon {
            get {
                object obj = ResourceManager.GetObject("axcrypticon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap axcrypticon128 {
            get {
                object obj = ResourceManager.GetObject("axcrypticon128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled &apos;{0}&apos;..
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start application for &apos;{0}&apos;..
        /// </summary>
        internal static string CannotStartApplication {
            get {
                return ResourceManager.GetString("CannotStartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write &apos;{0}&apos;..
        /// </summary>
        internal static string CannotWrite {
            get {
                return ResourceManager.GetString("CannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check for a newer version..
        /// </summary>
        internal static string ClickToCheckForNewerVersionTooltip {
            get {
                return ResourceManager.GetString("ClickToCheckForNewerVersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeremovestandbygreen32 {
            get {
                object obj = ResourceManager.GetObject("closeremovestandbygreen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeremovestandbyred32 {
            get {
                object obj = ResourceManager.GetObject("closeremovestandbyred32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decryptedfilered16 {
            get {
                object obj = ResourceManager.GetObject("decryptedfilered16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumed open. Try to Close the application, or use the Clean function to remove it.
        /// </summary>
        internal static string DecryptedFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents (*{0})|*{0}|All files (*.*)|*.*.
        /// </summary>
        internal static string DecryptedSaveAsFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogFilterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exists, choose a new name to save as.
        /// </summary>
        internal static string DecryptedSaveAsFileDialogTitle {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decryptedunknownkeyfilered16 {
            get {
                object obj = ResourceManager.GetObject("decryptedunknownkeyfilered16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passphrase has not been entered yet. Double-click to enter passphrase and Open, or right-click for options.
        /// </summary>
        internal static string DecryptedUnknownKeyFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedUnknownKeyFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to decrypt.
        /// </summary>
        internal static string DecryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("DecryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap decryptlockopen32 {
            get {
                object obj = ResourceManager.GetObject("decryptlockopen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Logged On to AxCrypt. Click to Log Out..
        /// </summary>
        internal static string DefaultEncryptionKeyIsIsetToolTip {
            get {
                return ResourceManager.GetString("DefaultEncryptionKeyIsIsetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt Files (*{0})|*{0}|All files (*.*)|*.*.
        /// </summary>
        internal static string EncryptedFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("EncryptedFileDialogFilterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted File.
        /// </summary>
        internal static string EncryptedSourceColumnHeader {
            get {
                return ResourceManager.GetString("EncryptedSourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to encrypt.
        /// </summary>
        internal static string EncryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exists, Save As.
        /// </summary>
        internal static string EncryptFileSaveAsDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileSaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap encryptionkeygreen32 {
            get {
                object obj = ResourceManager.GetObject("encryptionkeygreen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap encryptionkeyred32 {
            get {
                object obj = ResourceManager.GetObject("encryptionkeyred32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap encryptlock32 {
            get {
                object obj = ResourceManager.GetObject("encryptlock32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during processing of &apos;{0}&apos;..
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamationgreen16 {
            get {
                object obj = ResourceManager.GetObject("exclamationgreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamationgreen32 {
            get {
                object obj = ResourceManager.GetObject("exclamationgreen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is already encrypted..
        /// </summary>
        internal static string FileAlreadyEncrypted {
            get {
                return ResourceManager.GetString("FileAlreadyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileknownkeygreen16 {
            get {
                object obj = ResourceManager.GetObject("fileknownkeygreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed &apos;{0}&apos;..
        /// </summary>
        internal static string FileOperationFailed {
            get {
                return ResourceManager.GetString("FileOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpquestiongreen32 {
            get {
                object obj = ResourceManager.GetObject("helpquestiongreen32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inactivefilegreen16 {
            get {
                object obj = ResourceManager.GetObject("inactivefilegreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive file.
        /// </summary>
        internal static string InactiveFileToolTip {
            get {
                return ResourceManager.GetString("InactiveFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent state with &apos;{0}&apos;..
        /// </summary>
        internal static string InconsistentState {
            get {
                return ResourceManager.GetString("InconsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL..
        /// </summary>
        internal static string Invalid_URL {
            get {
                return ResourceManager.GetString("Invalid_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key for &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or path &apos;{0}&apos; is invalid for this..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart AxCrypt in order for the language change to take effect..
        /// </summary>
        internal static string LanguageChangeRestartPrompt {
            get {
                return ResourceManager.GetString("LanguageChangeRestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Off.
        /// </summary>
        internal static string LoggedOffStatusText {
            get {
                return ResourceManager.GetString("LoggedOffStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged On.
        /// </summary>
        internal static string LoggedOnStatusText {
            get {
                return ResourceManager.GetString("LoggedOnStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available! Click to download..
        /// </summary>
        internal static string NewVersionIsAvailableTooltip {
            get {
                return ResourceManager.GetString("NewVersionIsAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Logged Out of AxCrypt. Click to Log On..
        /// </summary>
        internal static string NoDefaultEncryptionKeySetToolTip {
            get {
                return ResourceManager.GetString("NoDefaultEncryptionKeySetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to check for updates..
        /// </summary>
        internal static string NoNeedToCheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("NoNeedToCheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is old. Please click to check for a newer version..
        /// </summary>
        internal static string OldVersionTooltip {
            get {
                return ResourceManager.GetString("OldVersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opendocument32 {
            get {
                object obj = ResourceManager.GetObject("opendocument32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file to decrypt and open.
        /// </summary>
        internal static string OpenEncryptedFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenEncryptedFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string OpenFileColumnHeader {
            get {
                return ResourceManager.GetString("OpenFileColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrases do not match.
        /// </summary>
        internal static string PassphraseVerificationMismatch {
            get {
                return ResourceManager.GetString("PassphraseVerificationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging Active Files.
        /// </summary>
        internal static string PurgingActiveFiles {
            get {
                return ResourceManager.GetString("PurgingActiveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refreshgreen {
            get {
                object obj = ResourceManager.GetObject("refreshgreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refreshred {
            get {
                object obj = ResourceManager.GetObject("refreshred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trashred16 {
            get {
                object obj = ResourceManager.GetObject("trashred16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to restore the AxCrypt application window..
        /// </summary>
        internal static string TrayBalloonTooltip {
            get {
                return ResourceManager.GetString("TrayBalloonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized error code failing with &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedError {
            get {
                return ResourceManager.GetString("UnrecognizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Status.
        /// </summary>
        internal static string UpdatingStatus {
            get {
                return ResourceManager.GetString("UpdatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to securely delete.
        /// </summary>
        internal static string WipeFileSelectFileDialogTitle {
            get {
                return ResourceManager.GetString("WipeFileSelectFileDialogTitle", resourceCulture);
            }
        }
    }
}
